### ISSUE TITLE
"Should be next Spymaster" indicator

### ISSUE THREAD

**Issue by jjzabkar** [hbx-luv/codetango#33]
Once a team is drafted, there should be an indicator to show which player on the team “should be spymaster”, evidenced by who has been spymaster least frequently relative to their teammates.

This will allow more even distribution of spymastering.

**Comment by bacontech** [comment]
Least frequently should be ratio based and not raw based on raw games.

**Comment by Matttaylor8910** [comment]
Implemented sorting by spymaster rate so the least frequent spymaster is always selected first
