### ISSUE TITLE
Edit Room Settings

### ISSUE THREAD

**Issue by Matttaylor8910** [hbx-luv/codetango#4]
We should allow people to update `firstTurnTimer` (defaulted to 180), `timer` (defaulted to 120), `guessIncrement` (defaulted to 30), and `enforceTimer` (defaulted to false, and we still need to implement logic for in https://github.com/Matttaylor8910/codetango/issues/36).

I could see us adding an email whitelist feature to rooms as well if random people joining your room ever became a problem.

**Comment by bacontech** [comment]
Bob going hard
